---
- hosts: all
  sudo: true
  tasks:
    - name: install mysql-server
      apt:
        name: mysql-server
        state: present
    - name: install php
      apt:
        name: php
        state: present
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: install composer
      apt:
        name: composer
        state: present

    - name: import git
      git:
        repo: 'https://github.com/peterm94/sde-group4.git'
        dest: /srv/checkout
    - name: init database
      shell: mysql Assignmentdb1 < /srv/checkout/v2/createtable.sql

    - name: configure nginx
      template: src=srv/checkout/nginx.conf dest=/etc/nginx/sites-available/default
      notify:
        restart nginx
