---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant
    src_root: /vagrant/v2
    db_name: Assignmentdb
  tasks:
    - name: install required packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - php5
        - php5-mysql
        - mysql-server
        - python-mysqldb

    # DB setup
    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        
    - name: Restore database
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /vagrant/dump.sql       

    - name: Upgrade database
      mysql_db:
        state: import
        name: "{{ db_name }}"
        target: /vagrant/v2/createtable.sql

    - name: Create DB user
      mysql_user: 
        name: abc
        password: abc
        priv: '*.*:ALL'
        state: present
        
    # Apache setup
    - name: Add our config
      template: 
       src=apacheconf.j2
       dest=/etc/apache2/sites-available/vagrant.conf
    
    - name: Remove the default config
      file:
        path=/etc/apache2/sites-enabled/000-default.conf
        state=absent
      notify:
        - reload apache

    - name: Enable the site
      file:
        src=/etc/apache2/sites-available/vagrant.conf
        dest=/etc/apache2/sites-enabled/vagrant.conf
        state=link
      notify:
        - reload apache


  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded
